import type { UITranslations } from '../types'

export const uiCn: UITranslations = {
  nav: {
    home: '首页',
    gameMechanics: '游戏机制',
    seasonMechanics: '赛季机制',
    tools: '工具',
    buildPlanner: 'Build模拟器',
    voidchartPlanner: '虚空星图规划器',
    about: '关于',
    impressum: '法律声明',
  },
  mobileNav: {
    menu: '菜单',
    closeMenu: '关闭菜单',
    language: '语言',
  },
  footer: {
    copyright: '© {year} TLI 宝典。保留所有权利。',
  },
  home: {
    latest: '最新',
    filterAll: '全部',
    filterGuides: '攻略',
    filterTools: '工具',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '战斗机制',
    gameSystems: '游戏系统',
    seasons1to4: '赛季 1-4',
    seasons5to8: '赛季 5-8',
    seasons9to11: '赛季 9-11',
    seasons13: '赛季 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防御',
    defencesDesc: '护甲、抗性和伤害减免',
    ailments: '异常状态',
    ailmentsDesc: '状态效果和持续伤害',
    melee: '近战',
    meleeDesc: ' steep Strike、多击和连击',
    spells: '法术',
    spellsDesc: '法术爆发、缠绕和连击',
    minions: '召唤物',
    minionsDesc: '召唤物及其运作方式',
    damageOverTime: '持续伤害',
    damageOverTimeDesc: '关于持续伤害的一切',
    buffsAndDebuffs: '增益与减益',
    buffsAndDebuffsDesc: '祝福、弱化等',
    auras: '光环',
    aurasDesc: '关于光环和封印法力的一切',
    curses: '诅咒',
    cursesDesc: '关于诅咒的一切',
    // Game Systems
    crafting: '打造',
    craftingDesc: '打造系统和机制',
    // Seasons
    darkSurge: '黑暗 surge',
    darkSurgeDesc: '黑暗 surge 赛季机制',
    blacksail: '黑帆',
    blacksailDesc: '黑帆赛季机制',
    cube: '魔方',
    cubeDesc: '魔方赛季机制',
    aterna: 'Aterna',
    aternaDesc: 'Aterna 赛季机制',
    nightmare: '噩梦',
    nightmareDesc: '噩梦赛季机制',
    whisperingMist: '低语之雾',
    whisperingMistDesc: '低语之雾赛季机制',
    clockworkBallet: '发条芭蕾',
    clockworkBalletDesc: '发条芭蕾赛季机制',
    theFrozenCanvas: '冰封画布',
    theFrozenCanvasDesc: '冰封画布赛季机制',
    arcana: '奥秘',
    arcanaDesc: '奥秘赛季机制',
    sandlord: '沙领主',
    sandlordDesc: '沙领主赛季机制',
    outlaw: ' outlaw',
    outlawDesc: ' outlaw 赛季机制',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm 赛季机制',
    vorax: 'Vorax',
    voraxDesc: 'Vorax 赛季机制',
  },
  support: {
    message: '支持我们 ❤️.',
  },
}
