import type { UITranslations } from '../types'

export const uiEn: UITranslations = {
  nav: {
    home: 'Home',
    gameMechanics: 'Game Mechanics',
    seasonMechanics: 'Season Mechanics',
    tools: 'Tools',
    buildPlanner: 'Build Planner',
    voidchartPlanner: 'VoidChart Planner',
    about: 'About',
    impressum: 'Impressum',
  },
  mobileNav: {
    menu: 'Menu',
    closeMenu: 'Close menu',
    language: 'Language',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: 'LATEST',
    filterAll: 'All',
    filterGuides: 'Guides',
    filterTools: 'Tools',
    filterUpdates: 'Updates',
  },
  menuCategories: {
    combatMechanics: 'COMBAT MECHANICS',
    gameSystems: 'GAME SYSTEMS',
    seasons1to4: 'SEASONS 1-4',
    seasons5to8: 'SEASONS 5-8',
    seasons9to11: 'SEASONS 9-11',
    seasons13: 'SEASONS 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: 'Defences',
    defencesDesc: 'Armor, resistance, and mitigation',
    ailments: 'Ailments',
    ailmentsDesc: 'Status effects and damage over time',
    melee: 'Melee',
    meleeDesc: 'Steep Strike, Multistrike, and Combo',
    spells: 'Spells',
    spellsDesc: 'Spellburst, Tangle, and Combo',
    minions: 'Minions',
    minionsDesc: 'Minions & how they work',
    damageOverTime: 'Damage over Time',
    damageOverTimeDesc: 'Everything about DoT\'s',
    buffsAndDebuffs: 'Buffs & Debuffs',
    buffsAndDebuffsDesc: 'Blessings, Weaken & more',
    auras: 'Auras',
    aurasDesc: 'Everything about Auras & Sealed Mana',
    curses: 'Curses',
    cursesDesc: 'Everything about curses',
    // Game Systems
    crafting: 'Crafting',
    craftingDesc: 'Crafting systems and mechanics',
    // Seasons
    darkSurge: 'Dark Surge',
    darkSurgeDesc: 'Dark Surge season mechanics',
    blacksail: 'Blacksail',
    blacksailDesc: 'Blacksail season mechanics',
    cube: 'Cube',
    cubeDesc: 'Cube season mechanics',
    aterna: 'Aterna',
    aternaDesc: 'Aterna season mechanics',
    nightmare: 'Nightmare',
    nightmareDesc: 'Nightmare season mechanics',
    whisperingMist: 'Whispering Mist',
    whisperingMistDesc: 'Whispering Mist season mechanics',
    clockworkBallet: 'Clockwork Ballet',
    clockworkBalletDesc: 'Clockwork Ballet season mechanics',
    theFrozenCanvas: 'The Frozen Canvas',
    theFrozenCanvasDesc: 'The Frozen Canvas season mechanics',
    arcana: 'Arcana',
    arcanaDesc: 'Arcana season mechanics',
    sandlord: 'Sandlord',
    sandlordDesc: 'Sandlord season mechanics',
    outlaw: 'Outlaw',
    outlawDesc: 'Outlaw season mechanics',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm season mechanics',
    vorax: 'Vorax',
    voraxDesc: 'Vorax season mechanics',
  },
  support: {
    message: 'Show your support ❤️.',
  },
}
