import type { UITranslations } from '../types'

export const uiJa: UITranslations = {
  nav: {
    home: 'ホーム',
    gameMechanics: 'ゲームシステム',
    seasonMechanics: 'シーズンシステム',
    tools: 'ツール',
    buildPlanner: 'ビルドプランナー',
    voidchartPlanner: 'ボイドチャートプランナー',
    about: '概要',
    impressum: '法的通知',
  },
  mobileNav: {
    menu: 'メニュー',
    closeMenu: 'メニューを閉じる',
    language: '言語',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: '最新',
    filterAll: 'すべて',
    filterGuides: 'ガイド',
    filterTools: 'ツール',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '戦闘システム',
    gameSystems: 'ゲームシステム',
    seasons1to4: 'シーズン 1-4',
    seasons5to8: 'シーズン 5-8',
    seasons9to11: 'シーズン 9-11',
    seasons13: 'シーズン 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防御',
    defencesDesc: 'アーマー、耐性、軽減',
    ailments: '状態異常',
    ailmentsDesc: '状態効果と継続ダメージ',
    melee: '近接',
    meleeDesc: 'Steep Strike、Multistrike、Combo',
    spells: 'スペル',
    spellsDesc: 'Spellburst、Tangle、Combo',
    minions: 'ミニオン',
    minionsDesc: 'ミニオンとその仕組み',
    damageOverTime: '継続ダメージ',
    damageOverTimeDesc: 'DoTについて全て',
    buffsAndDebuffs: 'バフとデバフ',
    buffsAndDebuffsDesc: '祝福、弱体化など',
    auras: 'オーラ',
    aurasDesc: 'オーラとシールドマナについて全て',
    curses: '呪い',
    cursesDesc: '呪いについて全て',
    // Game Systems
    crafting: 'クラフト',
    craftingDesc: 'クラフトシステムと仕組み',
    // Seasons
    darkSurge: 'ダークサージ',
    darkSurgeDesc: 'ダークサージシーズンシステム',
    blacksail: 'ブラックセイル',
    blacksailDesc: 'ブラックセイルシーズンシステム',
    cube: 'キューブ',
    cubeDesc: 'キューブシーズンシステム',
    aterna: 'アテルナ',
    aternaDesc: 'アテルナシーズンシステム',
    nightmare: 'ナイトメア',
    nightmareDesc: 'ナイトメアシーズンシステム',
    whisperingMist: 'ウィスパリングミスト',
    whisperingMistDesc: 'ウィスパリングミストシーズンシステム',
    clockworkBallet: 'クロックワークバレエ',
    clockworkBalletDesc: 'クロックワークバレエシーズンシステム',
    theFrozenCanvas: 'フローズンキャンバス',
    theFrozenCanvasDesc: 'フローズンキャンバスシーズンシステム',
    arcana: 'アルカナ',
    arcanaDesc: 'アルカナシーズンシステム',
    sandlord: 'サンドロード',
    sandlordDesc: 'サンドロードシーズンシステム',
    outlaw: 'アウトロー',
    outlawDesc: 'アウトローシーズンシステム',
    overrealm: 'オーバーレルム',
    overrealmDesc: 'オーバーレルムシーズンシステム',
    vorax: 'ボラックス',
    voraxDesc: 'ボラックスシーズンシステム',
  },
  support: {
    message: '応援してください ❤️.',
  },
}
