import type { UITranslations } from '../types'

export const uiKo: UITranslations = {
  nav: {
    home: '홈',
    gameMechanics: '게임 메커니즘',
    seasonMechanics: '시즌 메커니즘',
    tools: '도구',
    buildPlanner: '빌드 플래너',
    voidchartPlanner: '보이드 차트 플래너',
    about: '소개',
    impressum: '법적 고지',
  },
  mobileNav: {
    menu: '메뉴',
    closeMenu: '메뉴 닫기',
    language: '언어',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: '최신',
    filterAll: '전체',
    filterGuides: '가이드',
    filterTools: '도구',
    filterUpdates: '업데이트',
  },
  menuCategories: {
    combatMechanics: '전투 메커니즘',
    gameSystems: '게임 시스템',
    seasons1to4: '시즌 1-4',
    seasons5to8: '시즌 5-8',
    seasons9to11: '시즌 9-11',
    seasons13: '시즌 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '방어',
    defencesDesc: '방어구, 저항 및 피해 감소',
    ailments: '상태 이상',
    ailmentsDesc: '상태 효과 및 지속 피해',
    melee: '근접',
    meleeDesc: 'Steep Strike, Multistrike 및 Combo',
    spells: '주문',
    spellsDesc: 'Spellburst, Tangle 및 Combo',
    minions: '소환수',
    minionsDesc: '소환수 및 작동 방식',
    damageOverTime: '지속 피해',
    damageOverTimeDesc: '지속 피해에 관한 모든 것',
    buffsAndDebuffs: '버프 및 디버프',
    buffsAndDebuffsDesc: '축복, 약화 등',
    auras: '오라',
    aurasDesc: '오라 및 인 마나에 관한 모든 것',
    curses: '저주',
    cursesDesc: '저주에 관한 모든 것',
    // Game Systems
    crafting: '제작',
    craftingDesc: '제작 시스템 및 메커니즘',
    // Seasons
    darkSurge: '다크 서지',
    darkSurgeDesc: '다크 서지 시즌 메커니즘',
    blacksail: '블랙세일',
    blacksailDesc: '블랙세일 시즌 메커니즘',
    cube: '큐브',
    cubeDesc: '큐브 시즌 메커니즘',
    aterna: '아테르나',
    aternaDesc: '아테르나 시즌 메커니즘',
    nightmare: '나이트메어',
    nightmareDesc: '나이트메어 시즌 메커니즘',
    whisperingMist: '위스퍼링 미스트',
    whisperingMistDesc: '위스퍼링 미스트 시즌 메커니즘',
    clockworkBallet: '클락워크 발레',
    clockworkBalletDesc: '클락워크 발레 시즌 메커니즘',
    theFrozenCanvas: '프로즌 캔버스',
    theFrozenCanvasDesc: '프로즌 캔버스 시즌 메커니즘',
    arcana: '아르카나',
    arcanaDesc: '아르카나 시즌 메커니즘',
    sandlord: '샌드로드',
    sandlordDesc: '샌드로드 시즌 메커니즘',
    outlaw: '아웃로',
    outlawDesc: '아웃로 시즌 메커니즘',
    overrealm: '오버렐름',
    overrealmDesc: '오버렐름 시즌 메커니즘',
    vorax: '보락스',
    voraxDesc: '보락스 시즌 메커니즘',
  },
  support: {
    message: '응원해주세요 ❤️.',
  },
}
