import type { UITranslations } from '../types'

export const uiRu: UITranslations = {
  nav: {
    home: 'Главная',
    gameMechanics: 'Игровая Механика',
    seasonMechanics: 'Сезонная Механика',
    tools: 'Инструменты',
    buildPlanner: 'Планировщик Билдов',
    voidchartPlanner: 'Планировщик VoidChart',
    about: 'О Нас',
    impressum: 'Правовая Информация',
  },
  mobileNav: {
    menu: 'Меню',
    closeMenu: 'Закрыть меню',
    language: 'Язык',
  },
  footer: {
    copyright: '© {year} TLI Compendium. Все права защищены.',
  },
  home: {
    latest: 'ПОСЛЕДНЕЕ',
    filterAll: 'Все',
    filterGuides: 'Гайды',
    filterTools: 'Инструменты',
    filterUpdates: 'Обновления',
  },
  menuCategories: {
    combatMechanics: 'БОЕВАЯ МЕХАНИКА',
    gameSystems: 'ИГРОВЫЕ СИСТЕМЫ',
    seasons1to4: 'СЕЗОНЫ 1-4',
    seasons5to8: 'СЕЗОНЫ 5-8',
    seasons9to11: 'СЕЗОНЫ 9-11',
    seasons13: 'СЕЗОН 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: 'Защита',
    defencesDesc: 'Броня, сопротивление и поглощение',
    ailments: 'Недуги',
    ailmentsDesc: 'Статусные эффекты и урон со временем',
    melee: 'Ближний бой',
    meleeDesc: 'Steep Strike, Multistrike и Combo',
    spells: 'Заклинания',
    spellsDesc: 'Spellburst, Tangle и Combo',
    minions: 'Прислужники',
    minionsDesc: 'Прислужники и как они работают',
    damageOverTime: 'Урон со временем',
    damageOverTimeDesc: 'Все об уроне со временем',
    buffsAndDebuffs: 'Баффы и дебаффы',
    buffsAndDebuffsDesc: 'Благословения, ослабление и другое',
    auras: 'Ауры',
    aurasDesc: 'Все об аурах и запечатанной мане',
    curses: 'Проклятия',
    cursesDesc: 'Все о проклятиях',
    // Game Systems
    crafting: 'Крафт',
    craftingDesc: 'Системы и механики крафта',
    // Seasons
    darkSurge: 'Темный Выброс',
    darkSurgeDesc: 'Механика сезона Темный Выброс',
    blacksail: 'Черный Парус',
    blacksailDesc: 'Механика сезона Черный Парус',
    cube: 'Куб',
    cubeDesc: 'Механика сезона Куб',
    aterna: 'Атерна',
    aternaDesc: 'Механика сезона Атерна',
    nightmare: 'Кошмар',
    nightmareDesc: 'Механика сезона Кошмар',
    whisperingMist: 'Шепчущий Туман',
    whisperingMistDesc: 'Механика сезона Шепчущий Туман',
    clockworkBallet: 'Заводной Балет',
    clockworkBalletDesc: 'Механика сезона Заводной Балет',
    theFrozenCanvas: 'Замерзший Холст',
    theFrozenCanvasDesc: 'Механика сезона Замерзший Холст',
    arcana: 'Аркана',
    arcanaDesc: 'Механика сезона Аркана',
    sandlord: 'Песчаный Лорд',
    sandlordDesc: 'Механика сезона Песчаный Лорд',
    outlaw: 'Вне закона',
    outlawDesc: 'Механика сезона Вне закона',
    overrealm: 'Сверхмир',
    overrealmDesc: 'Механика сезона Сверхмир',
    vorax: 'Воракс',
    voraxDesc: 'Механика сезона Воракс',
  },
  support: {
    message: 'Поддержите нас ❤️.',
  },
}
