import type { UITranslations } from '../types'

export const uiTw: UITranslations = {
  nav: {
    home: '首頁',
    gameMechanics: '遊戲機制',
    seasonMechanics: '賽季機制',
    tools: '工具',
    buildPlanner: 'Build模擬器',
    voidchartPlanner: '虛空星圖規劃器',
    about: '關於',
    impressum: '法律聲明',
  },
  mobileNav: {
    menu: '選單',
    closeMenu: '關閉選單',
    language: '語言',
  },
  footer: {
    copyright: '© {year} TLI 寶典。保留所有權利。',
  },
  home: {
    latest: '最新',
    filterAll: '全部',
    filterGuides: '攻略',
    filterTools: '工具',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '戰鬥機制',
    gameSystems: '遊戲系統',
    seasons1to4: '賽季 1-4',
    seasons5to8: '賽季 5-8',
    seasons9to11: '賽季 9-11',
    seasons13: '賽季 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防禦',
    defencesDesc: '護甲、抗性和傷害減免',
    ailments: '異常狀態',
    ailmentsDesc: '狀態效果和持續傷害',
    melee: '近戰',
    meleeDesc: 'Steep Strike、Multistrike 和 Combo',
    spells: '法術',
    spellsDesc: '法術爆發、纏繞和連擊',
    minions: '召喚物',
    minionsDesc: '召喚物及其運作方式',
    damageOverTime: '持續傷害',
    damageOverTimeDesc: '關於持續傷害的一切',
    buffsAndDebuffs: '增益與減益',
    buffsAndDebuffsDesc: '祝福、弱化等',
    auras: '光環',
    aurasDesc: '關於光環和封印法力的一切',
    curses: '詛咒',
    cursesDesc: '關於詛咒的一切',
    // Game Systems
    crafting: '打造',
    craftingDesc: '打造系統和機制',
    // Seasons
    darkSurge: '黑暗湧動',
    darkSurgeDesc: '黑暗湧動賽季機制',
    blacksail: '黑帆',
    blacksailDesc: '黑帆賽季機制',
    cube: '魔方',
    cubeDesc: '魔方賽季機制',
    aterna: 'Aterna',
    aternaDesc: 'Aterna 賽季機制',
    nightmare: '噩夢',
    nightmareDesc: '噩夢賽季機制',
    whisperingMist: '低語之霧',
    whisperingMistDesc: '低語之霧賽季機制',
    clockworkBallet: '發條芭蕾',
    clockworkBalletDesc: '發條芭蕾賽季機制',
    theFrozenCanvas: '冰封畫布',
    theFrozenCanvasDesc: '冰封畫布賽季機制',
    arcana: '奧秘',
    arcanaDesc: '奧秘賽季機制',
    sandlord: '沙領主',
    sandlordDesc: '沙領主賽季機制',
    outlaw: 'Outlaw',
    outlawDesc: 'Outlaw 賽季機制',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm 賽季機制',
    vorax: 'Vorax',
    voraxDesc: 'Vorax 賽季機制',
  },
  support: {
    message: '支持我們 ❤️.',
  },
}
